### ISSUE TITLE
Unable to run tests with SCALE-MAMBA backend

### ISSUE THREAD

**Issue by psrkiran** [mc2-project/cerebro#5]
I followed the instructions as per cerebro documentation and setup everything. When I tried to run `python test_scripts/test_scale_mamba.py`, I got following error
```
terminate called after throwing an instance of 'circuit_error'
  what():  Circuit problem
Aborted (core dumped)
```

**Comment by ryandeng1** [comment]
Hi, I will look into this. Currently busy the next couple weeks due to moving.

**Comment by psrkiran** [comment]
Hello Ryan, it started working once ConversionCircuit-LSSS_to_GC.txt is generated. Thank you
