### ISSUE TITLE
Expect Cerebro to enhance the features of condition

### ISSUE THREAD

**Issue by cryptozhao** [mc2-project/cerebro#7]
We expect that Cerebro could support two features of condition for compiling: multiple comparisons in one condition, and multiple statements, like:
 if ((a < b) and (c >=d)) or (e != f):
     x = u + v
     y = s * t
     z = u / t
else:
     y = u - s
     z = y + t

**Comment by ryandeng1** [comment]
Currently working on it.

**Comment by ryandeng1** [comment]
@cryptozhao Do you have any other example code for your use case? It seems to work on the test `Programs/test_multi_cond/test_multi_cond.mpc`, but it never hurts to test it more.

**Comment by ryandeng1** [comment]
Closing for now. If any other issues come up with multi-conditionals, please bring them up and open a new issue and I'll take a look.
